name: 'w3booster-dev'
volumes:
  w3b-mongo:
services:
  mongo:
    image: 'mongo:latest'
    restart: always
    volumes:
      - 'w3b-mongo:/data/db'
    ports:
      - 127.0.0.1:27017:27017
  parse-dashboard:
    image: 'parseplatform/parse-dashboard:latest'
    ports:
      - '4040:4040'
    environment:
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
      - PARSE_DASHBOARD_SERVER_URL=https://localhost:25080/parse
      - PARSE_DASHBOARD_MASTER_KEY=${PARSE_MASTER_KEY:-local-master-key-change-me}
      - PARSE_DASHBOARD_APP_ID=PSBdEx46ycVok7grEcdOMKPMsLYUl1OZ
      - PARSE_DASHBOARD_APP_NAME=W3Booster
      - PARSE_DASHBOARD_USER_ID=psadmin
      - PARSE_DASHBOARD_USER_PASSWORD=${PARSE_DASHBOARD_USER_PASSWORD:-change-me}
      - MOUNT_PATH=/dashboard/

